# Camel Spring Boot
camel:
  springboot:
    name: ${project.artifactId}
    main-run-controller: true

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO
    
# Application
application:
  inputDir: "target/input/"
  outputDir: "target/output"
  xmlInputFactory: "com.ctc.wstx.stax.WstxInputFactory"
  xmlOutputFactory: "com.ctc.wstx.stax.WstxOutputFactory"
  xmlEventFactory: "com.ctc.wstx.stax.WstxEventFactory"