---
name: file-to-file
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  build:
    uses: gfulton-redhat/github-workflows/.github/workflows/maven.yaml@main
    secrets: inherit